services:
  frontend:
    build:
      context: ./frontend
    restart: always
    networks:
      - ytdl
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
    restart: always
    networks:
      - ytdl
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

networks:
  ytdl:
    external: true
